remote_theme: brianmaierjr/long-haul

title: Lokus Olkusz
description: Olkuski klub strzelecki Lokus

#url: http://brianmaierjr.github.com/long-haul
baseurl: "/lokus2"
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Strona główna
    url: /index.html
  - title: Kalendarz
    url: /kalendarz
  - title: Kontakt
    url: /kontakt

social:
  github: bjurga/lokus2
  #twitter: bjurga
  facebook: Lokus.olkusz
  email: lokus.olkusz@gmail.com
  #linkedin: bjurga

#google_analytics: "UA-58263416-1"

#disqus:
#    shortname: brianmaierjr
  
